### ISSUE TITLE
Run and CombinedRun timeout and path

### ISSUE THREAD

**Issue by awalterschulze** [Labrum/CheckIt#3]
I think it would be more helpful to the user if the CombinedRun and Run functions took in the runPath string and the timeout value.

func CombinedRun(runPath string, timeout time.Duration, args ...string) (out []byte, err error)
func Run(runPath string, timeout time.Duration, args ...string) (out []byte, stderr []byte, err error)

What do you think?

**Comment by Labrum** [comment]
It might be simpler to change the working directory to the runpath before the interface's Run() function is called, so that runPath does not have to be passed at all. I agree though it makes more sense for the CombinedRun and Run helper functions to implement the timeout. This makes the signatures:

func CombinedRun(timeout time.Duration, args ...string)(out []byte, err error)
func Run(timeout time.Duration, args ...string)(out []byte, err error)

**Comment by awalterschulze** [comment]
That is an interesting idea :)
Was that your idea with the timeout as well?

**Comment by awalterschulze** [comment]
Sounds like a good idea to hide the run path, but the user needs to create some files.
I guess he could just use relative paths.
Ok cool, please keep the runPath hidden then.

So the Box interface's Run method then becomes
Run(textAreas []string) ([]byte, error)
?

And the Run functions are as you suggested above.

**Comment by Labrum** [comment]
Yes, user created files will be relative to the runpath. Box interface's Run will be as you suggested.
